# Generated by Django 4.2.5 on 2023-09-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_accomplishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
