# Generated by Django 4.2.5 on 2023-09-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_accomplishment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=80)),
                ('duration', models.CharField(max_length=40)),
                ('details', models.TextField()),
            ],
        ),
    ]
