# Generated by Django 4.2.5 on 2023-09-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_education_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education_Detail',
            new_name='Educationdetail',
        ),
    ]
