# Generated by Django 4.2.5 on 2023-09-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_education_detail_educationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edudets', to='pages.education'),
        ),
    ]
