# Generated by Django 4.2.5 on 2023-09-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_educationdetail_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educationdetail',
            new_name='Education_Detail',
        ),
    ]
