# Generated by Django 4.2.5 on 2023-10-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_profiledetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledetails',
            old_name='descrition',
            new_name='description',
        ),
    ]
