# Generated by Django 4.2.5 on 2023-10-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User_Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "journey_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journey_planner.journey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journey_Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("cost", models.FloatField(default=0.0)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("maps_url", models.URLField(blank=True, max_length=300)),
                ("place_url", models.URLField(blank=True, max_length=300)),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "journey_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journey_planner.journey",
                    ),
                ),
            ],
        ),
    ]
